#!/usr/bin/env bash
# gen-types.sh — Supabase DB 스키마에서 TypeScript 타입 자동 생성
#
# 사용법:
#   bash scripts/gen-types.sh

set -euo pipefail

CENTRAL="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$CENTRAL"

# .env에서 토큰 로드
if [ -f .env ]; then
  export $(grep -v '^#' .env | xargs)
fi

if [ -z "${SUPABASE_ACCESS_TOKEN:-}" ]; then
  echo "❌ SUPABASE_ACCESS_TOKEN이 설정되지 않았습니다."
  echo "   .env 파일을 확인하세요."
  exit 1
fi

OUTPUT_DIR="$CENTRAL/types"
OUTPUT_FILE="$OUTPUT_DIR/database.gen.ts"

mkdir -p "$OUTPUT_DIR"

echo "=== Supabase 타입 생성 ==="

# 임시 파일에 생성
TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE"' EXIT

npx supabase gen types typescript --linked --schema public > "$TMPFILE"

# 검증: export type Database 포함 여부
if ! grep -q 'export type Database' "$TMPFILE"; then
  echo "❌ 생성된 타입에 'export type Database'가 없습니다."
  echo "   Supabase 연결 상태를 확인하세요."
  exit 1
fi

# 헤더 주석 + 생성 결과 저장
{
  echo "// This file is auto-generated by scripts/gen-types.sh"
  echo "// Do not edit manually. Run 'bash scripts/gen-types.sh' to regenerate."
  echo "// Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo ""
  cat "$TMPFILE"
} > "$OUTPUT_FILE"

echo "✅ 타입 생성 완료: $OUTPUT_FILE"
echo "   $(wc -l < "$OUTPUT_FILE") 줄"
